---
- name: Uninstall Insights
  hosts: "{{ hosts | default(omit) }}"
  become: true

  tasks:
    - name: Remove Insights
      ansible.builtin.yum:
        name: insights-client
        state: absent

- name: Register to Satellite
  hosts: "{{ hosts | default(omit) }}"
  become: true

  tasks:
    - name: Execute cURL
      command: cat /etc/motd
